#!/usr/bin/python3
from mcstatus import MinecraftServer

try:
    server = MinecraftServer.lookup("localhost:25565")
    status = server.status()
    print(status.players.online)
except:
    print("0")
